select * 
from gold.dim_products;



-- Find total customers by countries

select
	country,
	count(customer_key) as total_customers_by_country
from gold.dim_customers
group by country
order by total_customers_by_country desc;



-- Find total customers by gender
select
	gender,
	count(customer_key) as total_customers_by_gender
from gold.dim_customers
group by gender
order by total_customers_by_gender desc;


-- Find total products by category

select
	category,
	count(product_key) as total_products_by_category
from gold.dim_products
group by category
order by total_products_by_category desc;



-- What is the average costs in each category?

select
	category,
	avg(cost) as avg_cost_by_category
from gold.dim_products
group by category
order by avg_cost_by_category desc;



-- What is the total revenue generated for each category?

select
	p.category,
	sum(f.sales_amount) as total_revenue_by_category
from gold.fact_sales as f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.category
order by total_revenue_by_category;

-- What is the total revenue generated by each customer?

select
	c.customer_key,
    c.first_name,
    c.last_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by  
c.customer_key,
c.first_name,
c.last_name



-- What is the distribution of sold items across countries?

SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;